export const reportThresholds = {
    "Harassment": 30,
    "Fraud": 20,
    "Scam": 25,
    "Spam": 15,
    "Misinformation": 35,
    "Hate Speech": 40,
    "Threat": 50,
    "Violence": 40,
    "Child Exploitation": 100,
    "Sexual Content": 50,
    "Fake Account": 10,
    "Self-Harm": 20,
    "Graphic Content": 30,
    "Infringement": 15,
    "Illegal Goods and Services": 50,
    "Impersonation": 10,
    "Bullying": 10,
    "Terrorism/Extremism": 10,
    "Toxic Behavior": 10,
    "Malware/Phishing Link": 10,
    "Copyright Violation": 10,
    "Promoting Hate or Violence": 10,
    "Offensive Language": 10,
    "Dangerous Challenges": 10,
    "Adult Content": 10,
    "Discrimination": 10
  };
  